
const QC_REPORT_API_URL = 'https://script.google.com/macros/s/AKfycbxX3UnuRwNcYWpGhyWsz-WVopHttb3tM5Qe381lLSdPR7gkeHjKJrExFxmByYem1Toz/exec';
const QCReport=(function(){
 let cursor=new Date();cursor.setDate(1),data=null,initialized=false;
 const months=['JANUARI','FEBRUARI','MARET','APRIL','MEI','JUNI','JULI','AGUSTUS','SEPTEMBER','OKTOBER','NOVEMBER','DESEMBER'];
 const cfg={panelRepair:{label:'QC PANEL REPAIR',dateId:'qcPanelDates',detailId:'qcPanelDetail',badgeId:'qcPanelBadge'},painting:{label:'QC PAINTING',dateId:'qcPaintingDates',detailId:'qcPaintingDetail',badgeId:'qcPaintingBadge'},finalInspection:{label:'QC FINAL INSPECTION',dateId:'qcFinalDates',detailId:'qcFinalDetail',badgeId:'qcFinalBadge'}};
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))} function pad(n){return String(n).padStart(2,'0')}
 function setStatus(k,t){let d=document.getElementById('qcApiDot'),s=document.getElementById('qcApiStatus');if(d)d.className='api-dot '+(k||'');if(s)s.textContent=t||''}
 function api(){if(QC_REPORT_API_URL)return QC_REPORT_API_URL;let u=prompt('Masukkan URL Web App QC REPORT API (script.google.com/macros/s/.../exec):');if(u){u=u.trim();localStorage.setItem('QC_REPORT_API_URL',u);return u}return ''}
 function label(){let e=document.getElementById('qcMonthLabel');if(e)e.textContent=months[cursor.getMonth()]+' '+cursor.getFullYear()}
 function days(){return new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate()}
 function dk(r){return String(r&&r.tanggalISO||'').slice(0,10)} function today(){let d=new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}
 function renderDates(key){let c=cfg[key],w=document.getElementById(c.dateId);if(!w)return;let sec=data?.sections?.[key]||{},rows=sec.rows||[],daily=sec.daily||{},max=days(),td=today();w.innerHTML='';for(let d=1;d<=31;d++){let e=document.createElement('div');e.className='qc-day';if(d>max){e.style.visibility='hidden';w.appendChild(e);continue}let n=Number(daily[String(d)]||0),date=cursor.getFullYear()+'-'+pad(cursor.getMonth()+1)+'-'+pad(d);if(date===td)e.classList.add('today');if(n)e.classList.add('has');e.innerHTML='<div class="d">TGL</div><div class="n">'+n+'</div><div class="lab">'+pad(d)+' '+months[cursor.getMonth()].slice(0,3)+'</div>';e.onclick=()=>{w.querySelectorAll('.qc-day').forEach(x=>x.classList.remove('selected'));e.classList.add('selected');detail(key,date)};w.appendChild(e)}let auto=rows.find(r=>dk(r)===td)||rows[0];if(auto){let date=dk(auto),idx=Number(date.slice(8,10))-1,e=w.children[idx];if(e){e.classList.add('selected');detail(key,date)}}else detail(key,'');let b=document.getElementById(c.badgeId);if(b)b.textContent=rows.length+' UNIT'}
 function detail(key,date){let c=cfg[key],box=document.getElementById(c.detailId),rows=(data?.sections?.[key]?.rows||[]).filter(r=>!date||dk(r)===date);if(!date){box.innerHTML='<div class="qc-empty">Belum ada data QC pada bulan ini.</div>';return}let p=date.split('-'),title=p[2]+'/'+p[1]+'/'+p[0];if(!rows.length){box.innerHTML='<div class="qc-detail-title"><strong>'+esc(c.label)+' • '+title+'</strong><span>0 UNIT</span></div><div class="qc-empty">Tidak ada unit yang selesai QC pada tanggal tersebut.</div>';return}let h='<div class="qc-detail-title"><strong>'+esc(c.label)+' • '+title+'</strong><span>'+rows.length+' UNIT</span></div><div class="qc-table-wrap"><table class="qc-table"><thead><tr><th>NO</th><th>NO POLISI</th><th>NO PKB</th><th>TYPE</th><th>GROUP</th><th>SA</th><th>ASURANSI</th><th>PANEL</th><th>KERUSAKAN</th><th>HASIL QC</th><th>DEFECT</th><th>KETERANGAN</th><th>INSPECTOR</th></tr></thead><tbody>';rows.forEach((r,i)=>{h+='<tr><td>'+(i+1)+'</td><td>'+esc(r.noPolisi||'-')+'</td><td>'+esc(r.noPKB||'-')+'</td><td>'+esc(r.type||'-')+'</td><td>'+esc(r.group||'-')+'</td><td>'+esc(r.sa||'-')+'</td><td>'+esc(r.asuransi||'-')+'</td><td>'+esc(r.panel||'-')+'</td><td>'+esc(r.kerusakan||'-')+'</td><td>'+esc(r.hasilQC||'-')+'</td><td>'+esc(r.defect||'-')+'</td><td>'+esc(r.keterangan||'-')+'</td><td>'+esc(r.inspector||'-')+'</td></tr>'});h+='</tbody></table></div>';box.innerHTML=h}
 function render(){label();let m=data?.mtd||{};document.getElementById('qcTotal').textContent=m.total||0;document.getElementById('qcPanel').textContent=m.panelRepair||0;document.getElementById('qcPainting').textContent=m.painting||0;document.getElementById('qcFinal').textContent=m.finalInspection||0;['panelRepair','painting','finalInspection'].forEach(renderDates)}
 async function load(){let base=api();if(!base)return;setStatus('loading','Mengambil data QC...');try{let u=base+(base.includes('?')?'&':'?')+'action=qcReport&month='+(cursor.getMonth()+1)+'&year='+cursor.getFullYear()+'&ts='+Date.now(),r=await fetch(u,{method:'GET',cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);let j=await r.json();if(!j||j.success===false)throw Error(j?.error||'Response QC REPORT tidak valid');data=j;render();setStatus('','Terhubung • update '+new Date().toLocaleTimeString('id-ID'))}catch(e){setStatus('error','Gagal terhubung ke QC REPORT API');console.error(e);alert('QC REPORT API gagal diakses.\n'+(e.message||e))}}
 function init(){if(initialized)return;initialized=true;render();load()}function prevMonth(){cursor.setMonth(cursor.getMonth()-1);load()}function nextMonth(){cursor.setMonth(cursor.getMonth()+1);load()}function goToday(){let d=new Date();cursor=new Date(d.getFullYear(),d.getMonth(),1);load()}
 return {init,load,prevMonth,nextMonth,today:goToday};
})();
