(function(){'use strict';
const SSC_URL='https://ssc.toyota.astra.co.id/';
const A={vin:['NO RANGKA','NOMOR RANGKA','VIN'],pkb:['NO PKB','NO. PKB','PKB'],nopol:['NO POLISI','NO. POLISI','NOPOL'],type:['TYPE','TIPE','MODEL'],tglCetak:['TGL CETAK PKB','TANGGAL CETAK PKB','TGL PKB'],janji:['JANJI SELESAI','TGL JANJI SELESAI','TANGGAL JANJI SELESAI'],ket:['KETERANGAN','KETERANGAN UNIT','REMARK','REMARKS']};let active=null,status='',observer=null,scheduled=false;const $=id=>document.getElementById(id),norm=s=>String(s||'').trim().toUpperCase().replace(/\s+/g,' '),vinClean=s=>String(s||'').toUpperCase().replace(/[\s-]+/g,'').trim(),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){const t=$('toast');if(!t)return;t.textContent=s;t.classList.add('show');clearTimeout(t.__timer);t.__timer=setTimeout(()=>t.classList.remove('show'),2600)}
function mapHeaders(){const names=[...document.querySelectorAll('#tableHead th')].map(x=>norm(x.textContent)),m={};for(const k in A)m[k]=names.findIndex(n=>A[k].map(norm).includes(n));return m}
function text(row,i){return i<0||!row.cells[i]?'':String(row.cells[i].dataset.sscOriginalText||row.cells[i].textContent||'').trim()}
function data(row,m){return{row,map:m,nopol:text(row,m.nopol),type:text(row,m.type),vin:vinClean(text(row,m.vin)),pkb:text(row,m.pkb),tglCetak:text(row,m.tglCetak),janji:text(row,m.janji),ket:text(row,m.ket)}}
function parse(s){s=String(s||'').trim();let m=s.match(/(?:^|\s-\s)SSC:\s*TIDAK TERKENA\s*$/i)||s.match(/^SSC:\s*TIDAK TERKENA\s*$/i);if(m)return{status:'TIDAK TERKENA',detail:''};m=s.match(/(?:^|\s-\s)SSC:\s*TERKENA(?:\s*\(([^)]*)\)|\s*-\s*([^\r\n]+))?\s*$/i)||s.match(/^SSC:\s*TERKENA(?:\s*\(([^)]*)\)|\s*-\s*([^\r\n]+))?\s*$/i);return m?{status:'TERKENA',detail:String(m[1]||m[2]||'').trim()}:{status:'',detail:''}}
function writeOriginal(cell,s){if(!cell)return;cell.dataset.sscOriginalText=String(s||'');cell.title=String(s||'');cell.textContent=String(s||'')||'-'}
function renderCell(row,m){const c=row.cells[m.vin];if(!c)return;if(!c.dataset.sscOriginalText)c.dataset.sscOriginalText=String(c.textContent||'').trim();const d=data(row,m),p=parse(d.ket),valid=d.vin.length===17;c.classList.add('ssc-host');c.classList.toggle('ssc-cell-hit',p.status==='TERKENA');c.classList.toggle('ssc-cell-clear',p.status==='TIDAK TERKENA');let b='<span class="ssc-badge pending">BELUM ADA HASIL</span>';if(p.status==='TERKENA')b='<span class="ssc-badge hit">⚠ TERKENA SSC'+(p.detail?' • '+esc(p.detail):'')+'</span>';else if(p.status==='TIDAK TERKENA')b='<span class="ssc-badge clear">✓ TIDAK SSC</span>';c.innerHTML='<div class="ssc-vin-value">'+esc(d.vin||'-')+'</div>'+b+'<div class="ssc-cell-actions"><button class="ssc-mini" type="button" data-ssc-action="check" '+(valid?'':'disabled')+'>'+(p.status?'CEK ULANG':'CEK SSC')+'</button>'+(p.status?'<button class="ssc-mini secondary" type="button" data-ssc-action="copy">COPY WA</button>':'')+'</div>'+(!valid&&d.vin?'<small class="ssc-invalid">NO RANGKA harus 17 karakter</small>':'');c.dataset.sscEnhanced='1'}
function enhance(){scheduled=false;const m=mapHeaders();if(m.vin<0)return;document.querySelectorAll('#tableBody tr').forEach(r=>{if(!r.cells.length||r.querySelector('td.empty'))return;if(m.ket>=0&&r.cells[m.ket]&&!r.cells[m.ket].dataset.sscOriginalText)r.cells[m.ket].dataset.sscOriginalText=String(r.cells[m.ket].textContent||'').trim();if(r.cells[m.vin]&&r.cells[m.vin].dataset.sscEnhanced!=='1')renderCell(r,m)})}function schedule(){if(!scheduled){scheduled=true;requestAnimationFrame(enhance)}}
async function copy(s){try{if(navigator.clipboard&&isSecureContext)await navigator.clipboard.writeText(s);else{const t=document.createElement('textarea');t.value=s;t.readOnly=true;t.style.position='fixed';t.style.left='-9999px';document.body.appendChild(t);t.select();if(!document.execCommand('copy'))throw Error('copy gagal');t.remove()}return true}catch(e){console.error(e);return false}}
function wa(d,s,detail){return ['*HASIL PENGECEKAN SSC*','','No Polisi : '+(d.nopol||'-'),'Type : '+(d.type||'-'),'No Rangka : '+(d.vin||'-'),'Tgl Cetak PKB : '+(d.tglCetak||'-'),'Janji Selesai : '+(d.janji||'-'),'Hasil SSC : '+(s==='TERKENA'?'TERKENA SSC'+(detail?' - '+detail:''):'TIDAK TERKENA SSC')].join('\n')}
function preview(){const detail=$('sscDetail').value.trim(),has=!!status&&!!active;$('sscDetailWrap').hidden=status!=='TERKENA';$('sscNoBtn').classList.toggle('active',status==='TIDAK TERKENA');$('sscYesBtn').classList.toggle('active',status==='TERKENA');$('sscSaveBtn').disabled=!has;$('sscCopyWaBtn').disabled=!has;$('sscPreview').hidden=!has;if(has)$('sscWaPreview').textContent=wa(active,status,detail)}
function openToyota(copyVin){if(!active)return;const w=window.open(SSC_URL,'_blank','noopener');if(copyVin)copy(active.vin).then(ok=>toast(ok?'NO RANGKA disalin • Toyota SSC dibuka':'Toyota SSC dibuka • gagal copy NO RANGKA'));if(!w)toast('Popup diblokir browser. Izinkan popup untuk membuka Toyota SSC.')}
function show(d,open){active=d;status=parse(d.ket).status;$('sscNopol').textContent=d.nopol||'-';$('sscType').textContent=d.type||'-';$('sscVin').textContent=d.vin||'-';$('sscTglCetak').textContent=d.tglCetak||'-';$('sscJanji').textContent=d.janji||'-';$('sscCurrentKet').textContent=d.ket||'-';$('sscDetail').value=parse(d.ket).detail||'';$('sscSaveState').textContent='';$('sscModal').hidden=false;document.body.classList.add('ssc-modal-open');preview();if(open)openToyota(true)}function close(){if(!$('sscModal'))return;$('sscModal').hidden=true;document.body.classList.remove('ssc-modal-open');active=null;status=''}
function api(){return[window.__DATABASE_ACTIVE_API,window.DATABASE_API_URL,localStorage.getItem('DATABASE_API_URL'),window.DASHBOARD_API_URL,localStorage.getItem('DASHBOARD_API_URL'),'https://script.google.com/macros/s/AKfycbw5a2s4WxsPFTHfbXMI0DrZBiECdFcheOEbbwkFBY-9eypxT8ybe8lPMW--ALfDpcJY/exec'].map(x=>String(x||'').trim()).filter(Boolean)[0]||''}
function jsonp(url,ms){return new Promise((resolve,reject)=>{const cb='DMS_SSC_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const clean=()=>{try{delete window[cb]}catch(_){window[cb]=undefined}s.remove()},timer=setTimeout(()=>{if(!done){done=true;clean();reject(Error('JSONP timeout'))}},ms||25000);window[cb]=d=>{if(!done){done=true;clearTimeout(timer);clean();resolve(d)}};s.onerror=()=>{if(!done){done=true;clearTimeout(timer);clean();reject(Error('JSONP gagal'))}};const u=new URL(url);u.searchParams.set('callback',cb);s.src=u.toString();s.async=true;document.head.appendChild(s)})}
async function saveApi(p){const url=api();if(!url)throw Error('URL API Database tidak tersedia');const u=new URL(url);u.searchParams.set('action','sscSave');Object.keys(p).forEach(k=>u.searchParams.set(k,p[k]||''));u.searchParams.set('_',Date.now());let first;try{const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),25000);try{const r=await fetch(u.toString(),{method:'GET',cache:'no-store',redirect:'follow',signal:ctrl.signal});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(!d||d.success!==true)throw Error(d&&(d.error||d.message)||'Penyimpanan SSC ditolak API');return d}finally{clearTimeout(timer)}}catch(e){first=e}try{const d=await jsonp(u.toString(),25000);if(!d||d.success!==true)throw Error(d&&(d.error||d.message)||'Penyimpanan SSC ditolak API');return d}catch(e){throw Error((first?first.message+' | ':'')+e.message)}}
async function save(){if(!active||!status)return;if(active.vin.length!==17){toast('NO RANGKA harus 17 karakter.');return}const detail=$('sscDetail').value.trim(),btn=$('sscSaveBtn');btn.disabled=true;btn.textContent='MENYIMPAN...';$('sscSaveState').textContent='Menyimpan hasil ke kolom KETERANGAN...';try{const d=await saveApi({noPKB:active.pkb,noPolisi:active.nopol,noRangka:active.vin,status,detail});active.ket=String(d.keterangan||'').trim();$('sscCurrentKet').textContent=active.ket||'-';if(active.map.ket>=0&&active.row.cells[active.map.ket])writeOriginal(active.row.cells[active.map.ket],active.ket);if(active.row.cells[active.map.vin]){active.row.cells[active.map.vin].dataset.sscEnhanced='';renderCell(active.row,active.map)}$('sscSaveState').textContent='✓ Hasil SSC tersimpan ke KETERANGAN.';toast('Hasil SSC berhasil disimpan');preview()}catch(e){console.error(e);$('sscSaveState').textContent='Gagal menyimpan: '+(e.name==='AbortError'?'API timeout':e.message);toast('Gagal menyimpan hasil SSC')}finally{btn.textContent='SIMPAN KE KETERANGAN';btn.disabled=!status}}
function clickTable(e){const b=e.target.closest('[data-ssc-action]');if(!b)return;const row=b.closest('tr');if(!row)return;const m=mapHeaders();if(m.vin<0)return;const d=data(row,m);if(b.dataset.sscAction==='check'){if(d.vin.length!==17){toast('NO RANGKA harus 17 karakter.');return}show(d,true)}else if(b.dataset.sscAction==='copy'){const p=parse(d.ket);if(!p.status){toast('Belum ada hasil SSC untuk dicopy.');return}copy(wa(d,p.status,p.detail)).then(ok=>toast(ok?'Hasil SSC siap ditempel ke WhatsApp':'Gagal menyalin hasil SSC'))}}
function init(){const body=$('tableBody');if(!body||!$('sscModal'))return;body.addEventListener('click',clickTable);document.querySelectorAll('[data-ssc-close]').forEach(x=>x.addEventListener('click',close));$('sscOpenToyotaBtn').addEventListener('click',()=>openToyota(true));$('sscNoBtn').addEventListener('click',()=>{status='TIDAK TERKENA';preview()});$('sscYesBtn').addEventListener('click',()=>{status='TERKENA';preview();setTimeout(()=>$('sscDetail').focus(),0)});$('sscDetail').addEventListener('input',preview);$('sscCopyWaBtn').addEventListener('click',()=>{if(active&&status)copy(wa(active,status,$('sscDetail').value.trim())).then(ok=>toast(ok?'Hasil SSC siap ditempel ke WhatsApp':'Gagal menyalin hasil SSC'))});$('sscSaveBtn').addEventListener('click',save);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('sscModal').hidden)close()});observer=new MutationObserver(schedule);observer.observe(body,{childList:true,subtree:true});const h=$('tableHead');if(h)observer.observe(h,{childList:true,subtree:true});schedule()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();})();
